Assignment/Models/App.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Assignment.Models
{
    public class Application
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        [Required]
        public string Name { get; set; }
        [JsonProperty("apns_env")]
        public string ApnsEnv { get; set; }

        [JsonProperty("gcm_key")]
        public string GcmKey { get; set; }

        [JsonProperty("chrome_web_origin")]
        public string ChromeWebOrigin { get; set; }

        [JsonProperty("chrome_web_default_notification_icon")]
        public string ChromeWebDefaultNotificationIcon { get; set; }

        [JsonProperty("chrome_web_sub_domain")]
        public string ChromeWebSubDomain { get; set; }

        [JsonProperty("apns_p12")]
        public string ApnsP12 { get; set; }

        [JsonProperty("apns_p12_password")]
        public string ApnsP12Password { get; set; }

        [JsonProperty("android_gcm_sender_id")]
        public string AndroidGcmSenderId { get; set; }

        [JsonProperty("safari_apns_p12")]
        public string SafariApnsP12 { get; set; }

        [JsonProperty("safari_apns_p12_password")]
        public string SafariApnsP12Password { get; set; }

        [JsonProperty("additional_data_is_root_payload")]
        public bool AdditionalDataIsRootPayload { get; set; }

        [JsonProperty("organization_id")]
        public string OrganizationId { get; set; }

        [JsonProperty("site_name")]
        public string SiteName { get; set; }

        [JsonProperty("safari_site_origin")]
        public string SafariSiteOrigin { get; set; }

        [JsonProperty("safari_icon_256_256")]
        public string SafariIcon256 { get; set; }

        [JsonProperty("chrome_key")]
        public string ChromeKey { get; set; }
    }
}

Assignment/Models/AppSettings.cs
namespace Assignment.Models
{
    public class AppSettings
    {
        public string AppId { get; set; }
        public string RestAPIKey { get; set; }
        public string BaseAddress { get; set; }
        public string EndPoint { get; set; }
    }
}

Assignment/Models/ErrorViewModel.cs
using System;

namespace Assignment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment/Controllers/AppsController.cs
using Assignment.Interfaces;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers
{
    public class AppsController : Controller
    {
        private readonly ISvcApplication _svcApplication;
        public AppsController(ISvcApplication svcApplication)
        {
            _svcApplication = svcApplication;
        }

        //View all applications
        [Authorize(Roles = "Admin, Operation")]
        public IActionResult Index()
        {
            return View(_svcApplication.GetAllApplication());
        }

        //Create new application
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Application app)
        {
            if (ModelState.IsValid)
            {
                _svcApplication.CreateApplication(app);
                return RedirectToAction(nameof(Index));
            }
            return View(app);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(string id)
        {
            var app = _svcApplication.GetApplicationById(id);
            return View(app);
        }

        //edit application
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Application app)
        {
            if (ModelState.IsValid)
            {
                var result = _svcApplication.EditApplication(app);
                return RedirectToAction(nameof(Index));
            }
            return View(app);
        }
    }
}

Assignment/Controllers/HomeController.cs
using Assignment.Data;
using Assignment.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        UserManager<IdentityUser> _userManager;
        RoleManager<IdentityRole> _roleManager;
        public HomeController(ILogger<HomeController> logger, UserManager<IdentityUser> userManager,
        RoleManager<IdentityRole> roleManager)
        {
            _logger = logger;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment/Views/Apps/Create.cshtml
@model Assignment.Models.Application

@{
    ViewData["Title"] = "Create";
}

<h3>Create</h3>

<h4>Application</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApnsEnv" class="control-label"></label>
                <input asp-for="ApnsEnv" class="form-control" />
                <span asp-validation-for="ApnsEnv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GcmKey" class="control-label"></label>
                <input asp-for="GcmKey" class="form-control" />
                <span asp-validation-for="GcmKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeWebOrigin" class="control-label"></label>
                <input asp-for="ChromeWebOrigin" class="form-control" />
                <span asp-validation-for="ChromeWebOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeWebDefaultNotificationIcon" class="control-label"></label>
                <input asp-for="ChromeWebDefaultNotificationIcon" class="form-control" />
                <span asp-validation-for="ChromeWebDefaultNotificationIcon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeWebSubDomain" class="control-label"></label>
                <input asp-for="ChromeWebSubDomain" class="form-control" />
                <span asp-validation-for="ChromeWebSubDomain" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApnsP12" class="control-label"></label>
                <input asp-for="ApnsP12" class="form-control" />
                <span asp-validation-for="ApnsP12" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApnsP12Password" class="control-label"></label>
                <input asp-for="ApnsP12Password" class="form-control" />
                <span asp-validation-for="ApnsP12Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AndroidGcmSenderId" class="control-label"></label>
                <input asp-for="AndroidGcmSenderId" class="form-control" />
                <span asp-validation-for="AndroidGcmSenderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariApnsP12" class="control-label"></label>
                <input asp-for="SafariApnsP12" class="form-control" />
                <span asp-validation-for="SafariApnsP12" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariApnsP12Password" class="control-label"></label>
                <input asp-for="SafariApnsP12Password" class="form-control" />
                <span asp-validation-for="SafariApnsP12Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AdditionalDataIsRootPayload" /> @Html.DisplayNameFor(model => model.AdditionalDataIsRootPayload)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="OrganizationId" class="control-label"></label>
                <input asp-for="OrganizationId" class="form-control" />
                <span asp-validation-for="OrganizationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiteName" class="control-label"></label>
                <input asp-for="SiteName" class="form-control" />
                <span asp-validation-for="SiteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariSiteOrigin" class="control-label"></label>
                <input asp-for="SafariSiteOrigin" class="form-control" />
                <span asp-validation-for="SafariSiteOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariIcon256" class="control-label"></label>
                <input asp-for="SafariIcon256" class="form-control" />
                <span asp-validation-for="SafariIcon256" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeKey" class="control-label"></label>
                <input asp-for="ChromeKey" class="form-control" />
                <span asp-validation-for="ChromeKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment/Views/Apps/Edit.cshtml
@model Assignment.Models.Application

@{
    ViewData["Title"] = "Edit";
}

<h3>Edit</h3>

<h4>Application</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApnsEnv" class="control-label"></label>
                <input asp-for="ApnsEnv" class="form-control" />
                <span asp-validation-for="ApnsEnv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GcmKey" class="control-label"></label>
                <input asp-for="GcmKey" class="form-control" />
                <span asp-validation-for="GcmKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeWebOrigin" class="control-label"></label>
                <input asp-for="ChromeWebOrigin" class="form-control" />
                <span asp-validation-for="ChromeWebOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeWebDefaultNotificationIcon" class="control-label"></label>
                <input asp-for="ChromeWebDefaultNotificationIcon" class="form-control" />
                <span asp-validation-for="ChromeWebDefaultNotificationIcon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeWebSubDomain" class="control-label"></label>
                <input asp-for="ChromeWebSubDomain" class="form-control" />
                <span asp-validation-for="ChromeWebSubDomain" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApnsP12" class="control-label"></label>
                <input asp-for="ApnsP12" class="form-control" />
                <span asp-validation-for="ApnsP12" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApnsP12Password" class="control-label"></label>
                <input asp-for="ApnsP12Password" class="form-control" />
                <span asp-validation-for="ApnsP12Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AndroidGcmSenderId" class="control-label"></label>
                <input asp-for="AndroidGcmSenderId" class="form-control" />
                <span asp-validation-for="AndroidGcmSenderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariApnsP12" class="control-label"></label>
                <input asp-for="SafariApnsP12" class="form-control" />
                <span asp-validation-for="SafariApnsP12" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariApnsP12Password" class="control-label"></label>
                <input asp-for="SafariApnsP12Password" class="form-control" />
                <span asp-validation-for="SafariApnsP12Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AdditionalDataIsRootPayload" /> @Html.DisplayNameFor(model => model.AdditionalDataIsRootPayload)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="OrganizationId" class="control-label"></label>
                <input asp-for="OrganizationId" class="form-control" />
                <span asp-validation-for="OrganizationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SiteName" class="control-label"></label>
                <input asp-for="SiteName" class="form-control" />
                <span asp-validation-for="SiteName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariSiteOrigin" class="control-label"></label>
                <input asp-for="SafariSiteOrigin" class="form-control" />
                <span asp-validation-for="SafariSiteOrigin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafariIcon256" class="control-label"></label>
                <input asp-for="SafariIcon256" class="form-control" />
                <span asp-validation-for="SafariIcon256" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChromeKey" class="control-label"></label>
                <input asp-for="ChromeKey" class="form-control" />
                <span asp-validation-for="ChromeKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment/Views/Apps/Index.cshtml
@model IEnumerable<Assignment.Models.Application>

@{
    ViewData["Title"] = "Index";
}

<h3>Index</h3>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApnsEnv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GcmKey)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ChromeWebOrigin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ChromeWebDefaultNotificationIcon)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ChromeWebSubDomain)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApnsP12)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApnsP12Password)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AndroidGcmSenderId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SafariApnsP12)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SafariApnsP12Password)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AdditionalDataIsRootPayload)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrganizationId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SiteName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SafariSiteOrigin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SafariIcon256)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ChromeKey)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApnsEnv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GcmKey)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChromeWebOrigin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChromeWebDefaultNotificationIcon)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChromeWebSubDomain)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApnsP12)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApnsP12Password)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AndroidGcmSenderId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SafariApnsP12)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SafariApnsP12Password)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AdditionalDataIsRootPayload)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrganizationId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SiteName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SafariSiteOrigin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SafariIcon256)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ChromeKey)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Assignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apps" asp-action="Index">Apps</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>